version: '3'
volumes:
  db_data:
services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
      - db_data:/var/lib/mysq
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:443"
    depends_on:
      - db
