# Generated by Django 4.1.7 on 2023-03-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="title",
            field=models.CharField(default="", max_length=100),
        ),
    ]
