# Generated by Django 4.1.7 on 2023-03-23 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_issue_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("numIssues", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name="issue",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.project"
            ),
        ),
    ]
