# Generated by Django 4.1.7 on 2023-03-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_project_alter_issue_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="description",
            field=models.CharField(max_length=500),
        ),
    ]
